#!/bin/bash

. /usr/local/lib/reverse_proxy/add_server_to_reverse_proxy.sh
. /usr/local/lib/docker_utils/git_docker_build.sh
. /usr/local/lib/docker_utils/internal_docker_run.sh

function run_deploy() {
  local GIT_REPO=$1
  local IMAGE_NAME=$2
  local CONTAINER_NAME=$3
  local SERVICE_PORT=$4
  local CONTAINER_NETWORK=$5
  local PROXY_CONTAINER_NAME=$6
  local PROXY_NETWORK=$6
  local PROTOCOL=$7

  if [ -n "$GIT_REPO" ]
  then
    git_docker_build "$GIT_REPO" "$IMAGE_NAME"
  fi

  local CONTAINER_IP
  CONTAINER_IP=$(internal_docker_run "$IMAGE_NAME" "$CONTAINER_NAME" "$SERVICE_PORT" "$CONTAINER_NETWORK")
  add_server_to_reverse_proxy "$PROXY_CONTAINER_NAME" "$SERVER_NAME" "/" "$CONTAINER_IP" "$PROTOCOL" "$PROXY_NETWORK" "$CONTAINER_NETWORK" "$SERVICE_PORT"
}

run_deploy "$1" "$2" "$3" "$4" "$5" "$6" "$7"